name: C/C++ CI

on: [push]

jobs:
  linux_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Change directories
      run: cd build
    - name: cmake
      run: cmake -DCMAKE_BUILD_RELEASE=Debug
    - name: make
      run: make
